### ISSUE TITLE
Does not seem to be working with Windows 10.

### ISSUE THREAD

**Issue by RimBlock** [code34/-inidbi#1]
Hi,

Posted on your thread on the BI forums but no response.

Running Windows 10.
Have started with a fresh install of A3 (1.50.131969).
Installed inidbi v1.4 downloaded from your site (copied it to the A3 directory).
Unblocked iniDB.dll.
Setup the mod in the launcher.
Started A3.

Tried the following code (via debug but have tried in scripts as well).  No errors or results were returned.

call compile preProcessFile "\inidbi\init.sqf";
inidbExists = "TEST" call inidb_exists;
value = ["TEST", "GLOBAL", "units", "STRING"] call iniDB_read;
diag_log format["inidbExists: %1, value: %2",inidbExists, value];

Diag_log return (no errors about missing functions or anything like that).
"inidbExists: any, value: any"

If I am doing something wrong with the install I cannot see it.  I am suspecting it is either something to do with new 'features' in either the latest version of ARMA or in Windows 10.

I have extDB running on my server and am building a complete A3 conversion with someone else so this is not the first try at installing mods.  

If you require any other info then please just ask.

**Comment by code34** [comment]
hi :)

do You upgrade your server with the last vc Microsoft lib ?

-----Message d'origine-----
De : "RimBlock" notifications@github.com
Envoyé : ‎29/‎09/‎2015 10:59
À : "code34/-inidbi" -inidbi@noreply.github.com
Objet : [-inidbi] Does not seem to be working with Windows 10. (#1)

Hi,
Posted on your thread on the BI forums but no response.
Running Windows 10.
Have started with a fresh install of A3 (1.50.131969).
Installed inidbi v1.4 downloaded from your site (copied it to the A3 directory).
Unblocked iniDB.dll.
Setup the mod in the launcher.
Started A3.
Tried the following code (via debug but have tried in scripts as well). No errors or results were returned.
call compile preProcessFile "\inidbi\init.sqf";
inidbExists = "TEST" call inidb_exists;
value = ["TEST", "GLOBAL", "units", "STRING"] call iniDB_read;
diag_log format["inidbExists: %1, value: %2",inidbExists, value];
Diag_log return (no errors about missing functions or anything like that).
"inidbExists: any, value: any"
If I am doing something wrong with the install I cannot see it. I am suspecting it is either something to do with new 'features' in either the latest version of ARMA or in Windows 10.
I have extDB running on my server and am building a complete A3 conversion with someone else so this is not the first try at installing mods. 
If you require any other info then please just ask.

**Comment by RimBlock** [comment]
Hi,

Thanks for the reply.

I am using it as client only (along with XCam).

**Comment by RimBlock** [comment]
I also have Visual C++ 2013 Redistributable (x64) - 12.0.30501 installed.

**Comment by code34** [comment]
hi
i just answer on bis forum for your problem :)

```
  De : RimBlock <notifications@github.com>
```

 À : code34/-inidbi -inidbi@noreply.github.com 
Cc : Nicolas BOITEUX nicolas_boiteux@yahoo.fr 
 Envoyé le : Mercredi 30 septembre 2015 3h54
 Objet : Re: [-inidbi] Does not seem to be working with Windows 10. (#1)

I also have Visual C++ 2013 Redistributable (x64) - 12.0.30501 installed.—

**Comment by RimBlock** [comment]
Thanks.  With the A3 update from 1.5 -> 1.52 it now seems to be working fine.

Great mod.  Thanks for taking the time and making it available for everyone.
