### ISSUE TITLE
Question: Save Equipment in Creates

### ISSUE THREAD

**Issue by LaocheXe** [code34/-inidbi#2]
Hello, I wanted to know if there is a way to save innovatory items in creates/boxes/metal locks using this. I am in a PMC unit, and we are only allowed certain weapons, but if we find the weapons, we want to store them into lockers, or creates, and when the server restarts or shutdown we want the weapons to save so when we get on the weapons are still be there.

(We don't want to save equipment or gear on players and no save for player position) - Can you help me with my question?

**Comment by code34** [comment]
inidbi is depricated and do not anymore supported. You can save all informations you want with inidbi2 like classnames of the objects.

https://forums.bistudio.com/topic/186131-inidbi2-save-and-load-data-to-the-server-or-your-local-computer-without-databases/
